
CREATE TABLE USERS
(
	User_id int PRIMARY KEY,
	name VARCHAR(15) NOT NULL,
	surname VARCHAR(15) NOT NULL,
	phone VARCHAR(12) UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
)

CREATE TABLE CHARACTERS_SHEETS
(
	Sheet_id int PRIMARY KEY,
	FK_User_id int NOT NULL,
	name VARCHAR(15) NOT NULL,
	money int DEFAULT 0,
	description VARCHAR(8000),
	approved bit DEFAULT 0
)

CREATE TABLE EVENTS_TABLE
(
	Event_id int PRIMARY KEY,
	event_Title VARCHAR(255),
	event_date DATE,
	place VARCHAR(255),
	event_Description VARCHAR(2047) NOT NULL,
)

CREATE TABLE CHARACTERS_SHEETS_EVENT
(
	CHARACTERS_SHEETS_EVENT_Id int PRIMARY KEY,
	Sheet_id int FOREIGN KEY REFERENCES CHARACTERS_SHEETS(Sheet_id) NOT NULL,
	Event_id int FOREIGN KEY REFERENCES EVENTS_TABLE(Event_id) NOT NULL,
)
CREATE TABLE API_KEYS
(
	Id int PRIMARY KEY,
	APIKEY VARCHAR2(10) UNIQUE,
	Event_id int FOREIGN KEY REFERENCES EVENTS_TABLE(Event_id) NOT NULL,
	--Asp_User_id int FOREIGN KEY REFERENCES AspNetUser(Id) NOT NULL,
)
-- CONSTRAINTS
ALTER TABLE CHARACTERS_SHEETS 
ADD FOREIGN KEY (FK_User_id) REFERENCES USERS(User_id);
ALTER TABLE PREVILIGES
ADD FOREIGN KEY	(EVENTS_TABLE_id) REFERENCES EVENTS_TABLE(Event_id);
ALTER TABLE CHARACTERS_SHEETS_EVENT
ADD FOREIGN KEY	(Event_id) REFERENCES EVENTS_TABLE(Sheet_id);
ALTER TABLE CHARACTERS_SHEETS_EVENT
ADD FOREIGN KEY	(Sheet_id) REFERENCES CHARACTERS_SHEETS(Sheet_id);
