Drop table ASP_USER_EVENT;
Drop Table CHARACTERS_SHEETS;

Drop Table PLAYERS;
Drop Table API_KEYS;
Drop Table EVENTS_TABLE;

CREATE TABLE EVENTS_TABLE
(
	Event_id int,
	CONSTRAINT PK_Event_id PRIMARY KEY(Event_id),
	event_Title VARCHAR(255),
	event_date DATE,
	place VARCHAR(255),
	event_Description VARCHAR(2047) NOT NULL,
)

CREATE TABLE CHARACTERS_SHEETS
(
	Sheet_id int,
	CONSTRAINT PK_Sheet_id PRIMARY KEY(Sheet_id),
	Player_id_FK int NOT NULL,
	name VARCHAR(15) NOT NULL,
	money int DEFAULT 0,
	description VARCHAR(8000),
	approved bit DEFAULT 0,
	Event_id_FK INT,
	CONSTRAINT Event_CHARACTER_SHEET FOREIGN KEY(Event_id_FK)
	REFERENCES EVENTS_TABLE(Event_id),

)




CREATE TABLE API_KEYS
(
	Id int,
	CONSTRAINT PK_APIKEY_id PRIMARY KEY(id),
	APIKEY VARCHAR(10),
	CONSTRAINT APIKEY_UC UNIQUE(APIKEY),
	Event_id int  NOT NULL,
	CONSTRAINT API_KEY_EVENT_FK FOREIGN KEY(Event_id) REFERENCES EVENTS_TABLE(Event_id),
	Asp_User_id_FK nvarchar(450),
)

CREATE TABLE ASP_USER_EVENT
(
	ASP_USER_EVENT_Id int,
	CONSTRAINT PK_ASP_USER_EVENT_id PRIMARY KEY(ASP_USER_EVENT_Id),
	Asp_User_id_FK nvarchar(450),
	Event_id_FK int not null,
	CONSTRAINT EVENT_FK FOREIGN KEY (Event_id_fk) REFERENCES EVENTS_TABLE(Event_id)
)
CREATE TABLE PLAYERS
(
	Player_id int,
	CONSTRAINT PK_PLAYER_ID PRIMARY KEY(Player_id),
	name VARCHAR(15) NOT NULL,
	surname VARCHAR(15) NOT NULL,
	phone VARCHAR(12),
	email VARCHAR(255) NOT NULL,
	CONSTRAINT EMAIL_UC UNIQUE(email),
	Asp_User_id_FK nvarchar(450),
)


-- CONSTRAINTS
ALTER TABLE CHARACTERS_SHEETS 
ADD CONSTRAINT EVENT_CHARACTER_SHEET_FK FOREIGN KEY (Event_id_FK) REFERENCES EVENTS_TABLE(Event_id);
ALTER TABLE CHARACTERS_SHEETS 
ADD CONSTRAINT Event_Player_FK FOREIGN KEY (PLAYER_id_FK) REFERENCES PLAYERS(Player_id);

ALTER TABLE PLAYERS ADD CONSTRAINT AspUser_Player_FK FOREIGN KEY (Asp_User_id_FK) REFERENCES AspNetUsers(Id);
ALTER TABLE PLAYERS ALTER COLUMN ASP_User_id_FK nvarchar(450) Not null;

AlTER TABLE ASP_USER_EVENT
ADD CONSTRAINT AspUser_Event_FK FOREIGN KEY (Asp_User_id_FK) REFERENCES AspNetUsers(id);
ALTER TABLE ASP_USER_EVENT ALTER COLUMN ASP_User_id_FK nvarchar(450) Not null;
Alter table API_KEYS
ADD CONSTRAINT AspUser_APIKEY_FK FOREIGN key (Asp_User_id_FK) REFERENCES AspNetUsers(id);
ALTER TABLE API_KEYS ALTER COLUMN ASP_User_id_FK nvarchar(450) Not null;