default:
    trainer: ppo
    batch_size: 1024 
    buffer_size: 10240
    hidden_units: 128
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 1024
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.8
            encoding_size: 256
    lambd: 0.95
    epsilon: 0.2
    learning_rate: 3.0e-4
    beta: 5.0e-3

Shooter1PPO:
    batch_size: 512 
    buffer_size: 10240
    
Shooter2PPO:
    batch_size: 1024 
    buffer_size: 21800

Shooter3PPO:
    batch_size: 2024 
    buffer_size: 10240
  
    
